# Generated by Django 3.2.2 on 2022-02-24 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='frontend_name',
            new_name='friendly_name',
        ),
    ]
